language: python
sudo: required
services:
  - docker
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - ./bin/lint
  - ./bin/test
  - ./bin/generate_docs
  - ./bin/.travis_doc_url_fix
deploy:
  - provider: script
    script: bash bin/docker_push
    on:
      branch: master
  - provider: pages
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: docs/_build/html
    on:
      branch: master
    skip-cleanup: true
    target-branch: gh-pages
