language: python
sudo: required
services:
  - docker
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - ./bin/lint
  - ./bin/test
deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: master
