language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pydub
  - pip install pylint
  - pip install pylint-quotes
  - pip install pytest
script:
  - ./bin/lint
  - ./bin/test
